from enum import Enum


class SearchObject(Enum):
    REIHENHAUS = 1
    DOPPELHAUSHAELFTE = 2
    EINFAMILIENHAUS = 3
    ZWEIFAMILIENHAUS = 19
    MEHRFAMILIENHAUS = 4
    EIGENTUMSWOHNUNG_1_2_ZIMMER = 5
    EIGENTUMSWOHNUNG_3_4_ZIMMER = 6
    EIGENTUMSWOHNUNG_AB_5_ZIMMER = 7
    GEWERBEEINHEIT = 8
    WOHN_GESCHAEFTSHAUS = 13
    GARAGE = 9
    KFZ_STELLPLATZ = 10
    KFZ_STELLPLATZ_TIEFG = 11
    TEILEIGENTUM = 12
    GEWERBE_GRUNDSTUECK = 14
    BAUGRUND = 15
    UNBEBAUT = 16
    LF_GRUND = 17
    SONSTIGES = 18
